version: "3.1"
services:
  build-test:
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    container_name: build-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/services/app
      - "/var/services/app/node_modules"
    environment:
      - API_URL=${API_URL}
      - API_VERSION=${API_VERSION}
      - NEXT_PUBLIC_NEXT_SERVER=${NEXT_PUBLIC_NEXT_SERVER}
      - TZ=Asia/Seoul
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
